//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        public int Id { get; set; }
        public int AccountType { get; set; }
        public bool Processed { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public int Status { get; set; }
        public Nullable<System.Guid> NotificationHandle { get; set; }
        public Nullable<int> PinSetup { get; set; }
        public Nullable<System.Guid> FileAccessHandle { get; set; }
        public Nullable<System.DateTime> LastActive { get; set; }
        public Nullable<System.DateTime> ProfilePicChangeDate { get; set; }
        public Nullable<System.Guid> ProfilePicHandle { get; set; }
        public Nullable<int> ProfilePicId { get; set; }
        public string NotificationPlatform { get; set; }
        public string CurrencyCode { get; set; }
        public int VerificationLevel { get; set; }
        public string VerificationStatusNote { get; set; }
        public int VerificationStatus { get; set; }
        public bool DebitEnabled { get; set; }
        public decimal FiatBalance { get; set; }
        public decimal EliteDiscountPercentage { get; set; }
        public decimal SendingLimits { get; set; }
        public string DebitDisableReason { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<System.DateTime> StatusChnageDate { get; set; }
        public string ReferralCode { get; set; }
        public string RefereeCode { get; set; }
        public string StatusModifyBy { get; set; }
        public string ProfilePicFirebaseName { get; set; }
        public Nullable<System.DateTime> RefereeCodeDate { get; set; }
    }
}
